var nome = prompt("qual seu nome")
document.writeln(`olá ${nome}<br>`)
document.writeln(`seu nome tem ${ nome.length } letras <br>`)
document.writeln(`seu nome em maiusculas fica: ${nome.toUpperCase()} <br>`)
document.writeln(`seu nome em minúsculas fica: ${nome.toLowerCase()}`)